/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file is auto-generated by TanStack Router

import { Route as rootRouteImport } from "./routes/__root"
import { Route as MoreRouteImport } from "./routes/more"
import { Route as PolarRouteImport } from "./routes/polar"
import { Route as NutritionRouteImport } from "./routes/nutrition"
import { Route as TrainingRouteImport } from "./routes/training"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as PolarSessionIdRouteImport } from "./routes/polar.$sessionId"
import { Route as TrainingSessionRouteImport } from "./routes/training.session"

const MoreRoute = MoreRouteImport.update({
  id: "/more",
  path: "/more",
  getParentRoute: () => rootRouteImport,
} as any)
const PolarRoute = PolarRouteImport.update({
  id: "/polar",
  path: "/polar",
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: "/nutrition",
  path: "/nutrition",
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: "/training",
  path: "/training",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const PolarSessionIdRoute = PolarSessionIdRouteImport.update({
  id: "/polar/$sessionId",
  path: "/polar/$sessionId",
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingSessionRoute = TrainingSessionRouteImport.update({
  id: "/training/session",
  path: "/training/session",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/training": typeof TrainingRoute
  "/nutrition": typeof NutritionRoute
  "/polar": typeof PolarRoute
  "/more": typeof MoreRoute
  "/polar/$sessionId": typeof PolarSessionIdRoute
  "/training/session": typeof TrainingSessionRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/training": typeof TrainingRoute
  "/nutrition": typeof NutritionRoute
  "/polar": typeof PolarRoute
  "/more": typeof MoreRoute
  "/polar/$sessionId": typeof PolarSessionIdRoute
  "/training/session": typeof TrainingSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/training": typeof TrainingRoute
  "/nutrition": typeof NutritionRoute
  "/polar": typeof PolarRoute
  "/more": typeof MoreRoute
  "/polar/$sessionId": typeof PolarSessionIdRoute
  "/training/session": typeof TrainingSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/training"
    | "/nutrition"
    | "/polar"
    | "/more"
    | "/polar/$sessionId"
    | "/training/session"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/training"
    | "/nutrition"
    | "/polar"
    | "/more"
    | "/polar/$sessionId"
    | "/training/session"
  id:
    | "__root__"
    | "/"
    | "/training"
    | "/nutrition"
    | "/polar"
    | "/more"
    | "/polar/$sessionId"
    | "/training/session"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TrainingRoute: typeof TrainingRoute
  NutritionRoute: typeof NutritionRoute
  PolarRoute: typeof PolarRoute
  MoreRoute: typeof MoreRoute
  PolarSessionIdRoute: typeof PolarSessionIdRoute
  TrainingSessionRoute: typeof TrainingSessionRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": { id: "/"; path: "/"; fullPath: "/"; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    "/training": { id: "/training"; path: "/training"; fullPath: "/training"; preLoaderRoute: typeof TrainingRouteImport; parentRoute: typeof rootRouteImport }
    "/nutrition": { id: "/nutrition"; path: "/nutrition"; fullPath: "/nutrition"; preLoaderRoute: typeof NutritionRouteImport; parentRoute: typeof rootRouteImport }
    "/polar": { id: "/polar"; path: "/polar"; fullPath: "/polar"; preLoaderRoute: typeof PolarRouteImport; parentRoute: typeof rootRouteImport }
    "/more": { id: "/more"; path: "/more"; fullPath: "/more"; preLoaderRoute: typeof MoreRouteImport; parentRoute: typeof rootRouteImport }
    "/polar/$sessionId": { id: "/polar/$sessionId"; path: "/polar/$sessionId"; fullPath: "/polar/$sessionId"; preLoaderRoute: typeof PolarSessionIdRouteImport; parentRoute: typeof rootRouteImport }
    "/training/session": { id: "/training/session"; path: "/training/session"; fullPath: "/training/session"; preLoaderRoute: typeof TrainingSessionRouteImport; parentRoute: typeof rootRouteImport }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TrainingRoute: TrainingRoute,
  NutritionRoute: NutritionRoute,
  PolarRoute: PolarRoute,
  MoreRoute: MoreRoute,
  PolarSessionIdRoute: PolarSessionIdRoute,
  TrainingSessionRoute: TrainingSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
